# <center> Embedding

## Sources

https://github.com/UKPLab/sentence-transformers<br>

**Semantic Search**<br>
https://www.sbert.net/examples/sentence_transformer/applications/semantic-search/README.html<br>
https://www.sbert.net/examples/sparse_encoder/applications/semantic_search/README.html<br>

## Imports

In [197]:
%reset

In [1]:
import os
import re 

import numpy as np
import pandas as pd

# import faiss
import spacy
from spacy.tokenizer import Tokenizer

from sentence_transformers import SentenceTransformer
# from transformers import AutoModel, AutoTokenizer
# from transformers import CamembertTokenizer

from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.text_splitter import PythonCodeTextSplitter
# from langchain.text_splitter import SpacyTextSplitter
# from langchain.text_splitter import TokenTextSplitter
# from langchain.text_splitter import NLTKTextSplitter

import faiss
#%pip install faiss-cpu

#pd.set_option('display.max_columns', 5)
pd.set_option('display.max_colwidth', 100)
pd.set_option('display.max_rows', 20)

nlp = spacy.load("fr_core_news_md")

c:\Users\S589669\Documents\DEV\ABP-Doctheque\env_doctheque\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Load Documents

In [2]:
filename = "CSV/documents_cleaned.csv"
df = pd.read_csv(filename, index_col = [0])
titles = df["Titles_Cleaned"].values
documents = df["Documents_Cleaned"].values
print(type(titles), type(documents))
df

<class 'numpy.ndarray'> <class 'numpy.ndarray'>

,Ext,Titles,Titles_Cleaned,Documents_Cleaned
0,pptx,02 - Process réclamations,02 - process réclamations,gestion des reclamations organisation car animation et coordination journalière avec répartition...
1,pptx,AAV - Dérogations D08 - D10,aav - dérogations d08 - d10,aav - dérogations d08-d10 délégation équipe car délégation animateur analyste ru à indiquer dans...
2,pptx,Analyser un impayé,analyser un impayé,faire la cf04 avec la référence bancaire pour vérifier si paiements en retard on régularise l’en...
3,docx,Automatisation des impayés,automatisation des impayés,automatisation des impayes procédure à utiliser après analyse de la cf01 et cf04 et cf02 si néce...
4,docx,calcul remboursement,calcul remboursement,v/ 3.60 - 1.01 liste des reglements clients 822s506813 client 82200000081114473 sce societe civi...
5,docx,DEDOUBLONNAGE PACIFICA,dedoublonnage pacifica,procédure historique des modifications table des matières contenu description du processus conte...
6,pdf,DEROGATIONS A VALIDER PP07,derogations a valider pp07,procédure dérogations pp07 à valider rôle nom prénom rédaction miot francois contribution valida...
7,pdf,DEROGATIONS MISE à JOUR 04.2025,derogations mise à jour 04.2025,procédure procédure dérogations pp07 à valider rôle nom prénom rédaction guyon amélie contributi...
8,pdf,Dérogations PP07 - L'Essentiel,dérogations pp07 - l'essentiel,derogations a valider via la pp07 préambule - un assureur n’a pas à motiver un refus d’entrée du...
9,docx,FICHE DE RENSEIGNEMENT REGUL IMPAYE PACIFICA,fiche de renseignement regul impaye pacifica,fiche de renseignement : regularisation impayes pacifica client concerne nom : . prenom : . réf ...
10,pptx,INTEGRATION GUADELOUPE 17 10 2022 Suivi du lancement,integration guadeloupe 17 10 2022 suivi du lancement,integration guadeloupe cadre : ajustements précisions sur les activités partie commercialisation...
11,pptx,La Charte AVE Réclamations,la charte ave réclamations,la charte ave réclamations abp – conseil assistance réseau réclamations arrivant en direct du co...
12,pptx,Process Hors Norme (004),process hors norme 004,process hors norme 04/2024 sommaire contexte – définition du hors norme process archivage les mo...
13,pdf,RAJOUT DES CODES PROMOS,rajout des codes promos,procédure rajout codes promo si oubli conseiller rôle nom prénom rédaction hamon joel contributi...
14,pdf,RECLAMATIONS,reclamations,procédure reclamations rôle nom prénom rédaction le men veronique contribution validation histor...
15,pdf,REEDITION DES CONTRATS SUITE DYSFONCTIONNEMENT IMPRESSION,reedition des contrats suite dysfonctionnement impression,procédure réédition des contrats suite dysfonctionnement impression rôle nom prénom rédaction ug...
16,docx,Retour chèque suite impayé CR29,retour chèque suite impayé cr29,"ecc crcam du finistere société de courtage d'assurance 07 022 973 7, route du loch 29555 quimper..."
17,pdf,__TEST__LES ÉVÉNEMENTS DU CONTRAT,test les événements du contrat,souscription alertes souscription agence ccm as05 : cond. princ. sans antéced. + carte grise > 3...

## Tokenization

**Two different ways to tokenize**

tokenizer() AND nlp()<br>

nlp() recognizes slashes between words while tokenizer() does not.

In [7]:
n_doc = 0
document = df['Documents_Cleaned'][n_doc]

# Create a tokenizer with nlp.vocab
tokenizer = Tokenizer(nlp.vocab)
tokens = tokenizer(document)

# Default tokenizer
doc = nlp(document)
print(type(tokens), type(doc))

for i, j in zip(tokens[:100], doc[:100]):
    print(i, j)

<class 'spacy.tokens.doc.Doc'> <class 'spacy.tokens.doc.Doc'>
gestion gestion
des des
reclamations reclamations
organisation organisation
car car
animation animation
et et
coordination coordination
journalière journalière
avec avec
répartition répartition
des des
réclamations réclamations
une une
équipe équipe
polyvalente polyvalente
de de
18 18
conseillers conseillers
qui qui
traite traite
les les
réclamations réclamations
des des
journées journées
dédiées dédiées
et et
un un
suivi suivi
personnel personnel
des des
réclamations réclamations
prises prises
en en
charge charge
veille veille
permanente permanente
sur sur
les les
réclamations réclamations
en en
cours/suivi cours
par /
binôme suivi
si par
absence binôme
une si
boîte absence
mail une
dédiée boîte
aux mail
réclamations dédiée
sommaire aux
contexte réclamations
objectifs sommaire
detail contexte
de objectifs
la detail
procedure de
demandes la
de procedure
renseignements demandes
assistance de
car renseignements
conversation assistance
à car
trois conversation
réclamations à
analyse trois
décision réclamations
/pec analyse
regularisation décision
rédaction /pec
de regularisation
la rédaction
fiche de
pec la
envoi fiche
à pec
usp envoi
pour à
traitement usp
annexes pour
organigramme traitement
écoute annexes
client organigramme
par écoute
cr client
annuaire par
ugs cr
coordonnées annuaire
utiles ugs
contexte coordonnées
car utiles
est contexte
en car
charge est
du en
traitement charge
des du

In [3]:
def remove_punct_digit(text):
    doc = nlp(text)
    return [token for token in doc if not (token.is_punct or token.is_digit)]

def remove_stop_words_punct(text):
    doc = nlp(text)
    return [token for token in doc if not (token.is_stop or token.is_punct)]

df_tokens = df.copy()
df_tokens['Titles_Token'] = df_tokens['Titles_Cleaned'].apply(remove_punct_digit)
df_tokens['Documents_Token'] = df_tokens['Documents_Cleaned'].apply(remove_punct_digit)
# df_tokens['Titles_Token'] = df_tokens['Titles_Cleaned'].apply(remove_stop_words_punct)
# df_tokens['Documents_Token'] = df_tokens['Documents_Cleaned'].apply(remove_stop_words_punct)
df_tokens.drop(columns = ['Titles_Cleaned', 'Documents_Cleaned'], inplace = True)
df_tokens

,Ext,Titles,Titles_Token,Documents_Token
0,pptx,02 - Process réclamations,"[process, réclamations]","[gestion, des, reclamations, organisation, car, animation, et, coordination, journalière, avec, ..."
1,pptx,AAV - Dérogations D08 - D10,"[aav, dérogations, d08, d10]","[aav, dérogations, d08-d10, délégation, équipe, car, délégation, animateur, analyste, ru, à, ind..."
2,pptx,Analyser un impayé,"[analyser, un, impayé]","[faire, la, cf04, avec, la, référence, bancaire, pour, vérifier, si, paiements, en, retard, on, ..."
3,docx,Automatisation des impayés,"[automatisation, des, impayés]","[automatisation, des, impayes, procédure, à, utiliser, après, analyse, de, la, cf01, et, cf04, e..."
4,docx,calcul remboursement,"[calcul, remboursement]","[v/, 3.60, 1.01, liste, des, reglements, clients, 822s506813, client, sce, societe, civile, d', ..."
5,docx,DEDOUBLONNAGE PACIFICA,"[dedoublonnage, pacifica]","[procédure, historique, des, modifications, table, des, matières, contenu, description, du, proc..."
6,pdf,DEROGATIONS A VALIDER PP07,"[derogations, a, valider, pp07]","[procédure, dérogations, pp07, à, valider, rôle, nom, prénom, rédaction, miot, francois, contrib..."
7,pdf,DEROGATIONS MISE à JOUR 04.2025,"[derogations, mise, à, jour, 04.2025]","[procédure, procédure, dérogations, pp07, à, valider, rôle, nom, prénom, rédaction, guyon, améli..."
8,pdf,Dérogations PP07 - L'Essentiel,"[dérogations, pp07, l', essentiel]","[derogations, a, valider, via, la, pp07, préambule, un, assureur, n’, a, pas, à, motiver, un, re..."
9,docx,FICHE DE RENSEIGNEMENT REGUL IMPAYE PACIFICA,"[fiche, de, renseignement, regul, impaye, pacifica]","[fiche, de, renseignement, , regularisation, impayes, pacifica, client, concerne, nom, , preno..."
10,pptx,INTEGRATION GUADELOUPE 17 10 2022 Suivi du lancement,"[integration, guadeloupe, suivi, du, lancement]","[integration, guadeloupe, cadre, ajustements, précisions, sur, les, activités, partie, commercia..."
11,pptx,La Charte AVE Réclamations,"[la, charte, ave, réclamations]","[la, charte, ave, réclamations, abp, conseil, assistance, réseau, réclamations, arrivant, en, di..."
12,pptx,Process Hors Norme (004),"[process, hors, norme]","[process, hors, norme, 04/2024, sommaire, contexte, définition, du, hors, norme, process, archiv..."
13,pdf,RAJOUT DES CODES PROMOS,"[rajout, des, codes, promos]","[procédure, rajout, codes, promo, si, oubli, conseiller, rôle, nom, prénom, rédaction, hamon, jo..."
14,pdf,RECLAMATIONS,[reclamations],"[procédure, reclamations, rôle, nom, prénom, rédaction, le, men, veronique, contribution, valida..."
15,pdf,REEDITION DES CONTRATS SUITE DYSFONCTIONNEMENT IMPRESSION,"[reedition, des, contrats, suite, dysfonctionnement, impression]","[procédure, réédition, des, contrats, suite, dysfonctionnement, impression, rôle, nom, prénom, r..."
16,docx,Retour chèque suite impayé CR29,"[retour, chèque, suite, impayé, cr29]","[ecc, crcam, du, finistere, société, de, courtage, d', assurance, route, du, loch, quimper, cede..."
17,pdf,__TEST__LES ÉVÉNEMENTS DU CONTRAT,"[test, les, événements, du, contrat]","[souscription, alertes, souscription, agence, ccm, as05, cond, princ, sans, antéced, +, carte, g..."

**Rebuild document from tokens**

NOT WORKING

In [181]:
n_doc = 0
document = documents[n_doc]
tokens = nlp(document)

document_ = ' '.join([token.text for token in tokens])
print(document)
print(document_)

gestion des reclamations organisation car animation et coordination journalière avec répartition des réclamations une équipe polyvalente de 18 conseillers qui traite les réclamations des journées dédiées et un suivi personnel des réclamations prises en charge veille permanente sur les réclamations en cours/suivi par binôme si absence une boîte mail dédiée aux réclamations sommaire contexte objectifs detail de la procedure demandes de renseignements assistance car conversation à trois réclamations analyse décision /pec regularisation rédaction de la fiche pec envoi à usp pour traitement annexes organigramme écoute client par cr annuaire ugs coordonnées utiles contexte car est en charge du traitement des demandes de renseignements et des réclamations clients sur le périmètre iard part et pro et sur la prévoyance part et pro objectifs traitement en amont des demandes de renseignements en soutien des conseillers traitement des réclamations saisies en ave by caesar en recherchant la satisfaction client final et conseiller crb rechercher des solutions gagnant-gagnant detail de la procedure demandes de renseignements prélèvements des cotisations problématiques de résiliations non saisies ou refusées. proposition de conversation à trois client/conseiller/ugs afin de déterminer si la question relève d’une explication ou d’une réclamation test en cours de validation filtre service écoute qui propose au conseiller de nous appeler pour l’accompagner dans la recherche d’explication avec possibilité de conversation à trois client/conseiller/car test en cours de validation questions liées à l’assistance, à la gestion des sinistres les mots pour le dire detail de la procedure réclamations tout courrier de réclamation client adressé au pôle doit être saisie immédiatement et l’accusé réception envoyé au client tamponné et signé toute réclamation doit être prise en charge dans les 2 jours ouvrés suivant son enregistrement analyse vérifier le bien fondé de la réclamation erreur ca: dysfonctionnement, défaut de conseil apporter des explications claires et précises proposer une prise en charge commerciale à leur niveau si justifiée pour préserver la relation client apporter des explications claires et précises pour faciliter les réponses des conseillers et services écoute et expliquer les calculs si pec en l’absence d’erreur ca retour au conseiller et/ou service écoute en indiquant que le pôle ne prend pas en charge detail de la procedure réclamations tableaux de suivi individuel à votre disposition : s:\dab-abp-car\equip\03- apporter notre expertise aux crb\tableaux individuels suivi reclamations en cours régularisation décision/prise en charge la décision de prise en charge financière appartient à chaque cr. délégation au pôle jusqu’à 1000 € responsable pôle: 1000 € responsable unité: 500 € animateur –analyste: 300 € au-delà de 1000 €, si: réclamation arrivant en direct du conseiller : transférer la demande de pec à mon ru qui fera suivre au délégataire de la cr réclamation arrivant en groupe de discussion via service écoute client : transférer la demande de pec dans l’ave afin que le service écoute la fasse signer par le délégataire de la cr exception en cr22 où il faut envoyer la fiche au ru pour décision alexandre blanchard préconiser la rétroactivité de deux ans validée par le service juridique responsabiliser le client qui a tardé à nous signaler une erreur, un doublon, alors qu’il est prélevé et reçoit des documents tous les ans l’invitant à vérifier la conformité de son contrat et à nous signaler tout changement concernant le risque assuré. solution gagnant/gagnant. sauf: - dans les cas de dossier de succession partiellement traité. -si c’est le client et non le conseiller qui réclame et qu’il y a bien erreur ca la prise en charge devra alors être totale. régularisation fiche pec \\cpcapd2burv2.zcam.ztech\cap10burs\dab-abp-car\equip\03- apporter notre expertise aux crb\réclamations\00 - fiche pec\fiche délégation prise en charge vierge.docm rédiger la fiche pec, l’enregistrer sous pec pole lien ci-dessous , la présenter et la faire signer par le délégataire ou l’envoyer via ave pour qu’elle soit signée par le délégataire de la cr "s:\dab-abp-car\equip\03 - process\05 - réclamations\la charte ave réclamations.pptx« envoyer la fiche pec à l’usp par mail pour saisie de l’opération comptable et archivage : impayespacifica@ca-bretagne.fr alimenter l’ave par un commentaire en indiquant que la pec sera versée d’ici quelques jours sur le compte client. organigramme satisfaction clients cr822 responsable: laurence liscouet chargés qualité: lydie decruz 8223333 melanie piednoir 822 3933 gwenaëlle caigneaux 822 3379 marina guerif 8223140 organigramme ecoute clients cr829 responsable: isabelle cueff chargés qualité: florence delaloy 829 0680 arnaud le boedec 829 0496 organigramme qualité et satisfaction clients cr836 responsable: benoit eucheloup pôle amélioration continue : pôle écoute clients : berengere poulain 8363542 		 sophie dennequin 836 3724 fabrice guillemin 836 3432 laetitia josse 836 3874 sophie bonniou 8363809 angélique desouches 836 3695 rozenn briens 8363369 pôle sav réseau : anne mailleux 836 3929 transfert au pôle ecoute ou sav en fonction de l’origine organigramme ecoute clients cr860 responsable: françoise gueguen talmon chargés qualité: catherine lagarrosse 8607566 fanny le beller 8607610 marine le bris 8607550 caroline mauffret 8607601 nathalie serre 8607596 les ugs une implantation nationale au cœur des territoires 21 ugs 13 iard + 1 5 ugs pj + 1 3 ugs spécialisées dsin organigramme dsin 10-2021 - 6 ugs pj : rouen, aix en pce, rennes, bordeaux, caen, grenoble - pôle technique - rtn iard pro/corp/rc/ auto/nh - partenariats fraude 3 ugrs spécialisées montpellier – saint etienne - poitiers récolte, garantie locative, atm, entreprise et gestions externalisées 7 ugs iard : clermont fd , rennes, orléans, poitiers, metz, arras, la roche s/ yon 7 ugs iard : rouen, lyon, pau, montpellier, aix, strasbourg, dijon activités : - moa - pilotage - statistiques - planification activités : - budget - audit et projets - effectifs opérat . - logistique - communication format adresse mail : prénom.nom@ca-pacifica.fr dsin – pôle iard 1 s05 rennes s04 clermont s07 orléans s08 poitiers s09 metz s12 arras s13 lr/ yon pacifica – ugs de rennes 14 juin 2023 dsin – pôle iard 2 s01 rouen s02 lyon s03 pau s11 strasbourg s06 montpellier s10 aix dijon en 2023 pacifica – ugs de rennes 14 juin 2023 dsin – pôle pj pacifica – ugs de rennes 14 juin 2023 aix pj bordeaux rennes pj rouen pj caen 6ème pj à grenoble ouverture en septembre pôle rtn dsin – pôle activites specialisees pacifica – ugs de rennes 14 juin 2023 ugse poitiers sr1 montpellier saint etienne sr2 annuaire ugs sinistres annuaire ugs pj et ugrs annuaire assistance coordonnees utiles service telephone mail ugs 0800 810 812 gestionsinistre01@pacifica.fr ref sinistre en objet gestion des sinistres agri adresse générale gestionsr1@pacifica.fr europ assistance clientservices@europ-assistance.fr service consommateur pck ugpciereclamationsclients@ca-pacifica.fr atm 09 70 80 92 81 reclamations-crca-lcl@spb.eu pj 0800 813 810 pj@pacifica.fr ref sinistre en objet ugp cie pro 0810 20 25 20 ugpciepro@ca-pacifica.fr ugp cie part 0810 20 25 20 ugpciepart@ca-pacifica.fr departeme nt sante 09 77 40 50 00 infosante@departement-santé.com ugr 0800 810 816 ugr@ca-pacifica.fr specifica/finaxy 0801 907 762 gestion-part1@ca-specifica.fr
gestion des reclamations organisation car animation et coordination journalière avec répartition des réclamations une équipe polyvalente de 18 conseillers qui traite les réclamations des journées dédiées et un suivi personnel des réclamations prises en charge veille permanente sur les réclamations en cours / suivi par binôme si absence une boîte mail dédiée aux réclamations sommaire contexte objectifs detail de la procedure demandes de renseignements assistance car conversation à trois réclamations analyse décision /pec regularisation rédaction de la fiche pec envoi à usp pour traitement annexes organigramme écoute client par cr annuaire ugs coordonnées utiles contexte car est en charge du traitement des demandes de renseignements et des réclamations clients sur le périmètre iard part et pro et sur la prévoyance part et pro objectifs traitement en amont des demandes de renseignements en soutien des conseillers traitement des réclamations saisies en ave by caesar en recherchant la satisfaction client final et conseiller crb rechercher des solutions gagnant - gagnant detail de la procedure demandes de renseignements prélèvements des cotisations problématiques de résiliations non saisies ou refusées . proposition de conversation à trois client / conseiller / ugs afin de déterminer si la question relève d’ une explication ou d’ une réclamation test en cours de validation filtre service écoute qui propose au conseiller de nous appeler pour l’ accompagner dans la recherche d’ explication avec possibilité de conversation à trois client / conseiller / car test en cours de validation questions liées à l’ assistance , à la gestion des sinistres les mots pour le dire detail de la procedure réclamations tout courrier de réclamation client adressé au pôle doit être saisie immédiatement et l’ accusé réception envoyé au client tamponné et signé toute réclamation doit être prise en charge dans les 2 jours ouvrés suivant son enregistrement analyse vérifier le bien fondé de la réclamation erreur ca : dysfonctionnement , défaut de conseil apporter des explications claires et précises proposer une prise en charge commerciale à leur niveau si justifiée pour préserver la relation client apporter des explications claires et précises pour faciliter les réponses des conseillers et services écoute et expliquer les calculs si pec en l’ absence d’ erreur ca retour au conseiller et / ou service écoute en indiquant que le pôle ne prend pas en charge detail de la procedure réclamations tableaux de suivi individuel à votre disposition : s:\dab - abp - car\equip\03- apporter notre expertise aux crb\tableaux individuels suivi reclamations en cours régularisation décision / prise en charge la décision de prise en charge financière appartient à chaque cr . délégation au pôle jusqu’ à 1000 € responsable pôle : 1000 € responsable unité : 500 € animateur – analyste : 300 € au-delà de 1000 € , si : réclamation arrivant en direct du conseiller : transférer la demande de pec à mon ru qui fera suivre au délégataire de la cr réclamation arrivant en groupe de discussion via service écoute client : transférer la demande de pec dans l’ ave afin que le service écoute la fasse signer par le délégataire de la cr exception en cr22 où il faut envoyer la fiche au ru pour décision alexandre blanchard préconiser la rétroactivité de deux ans validée par le service juridique responsabiliser le client qui a tardé à nous signaler une erreur , un doublon , alors qu’ il est prélevé et reçoit des documents tous les ans l’ invitant à vérifier la conformité de son contrat et à nous signaler tout changement concernant le risque assuré . solution gagnant / gagnant . sauf : - dans les cas de dossier de succession partiellement traité . -si c’ est le client et non le conseiller qui réclame et qu’ il y a bien erreur ca la prise en charge devra alors être totale . régularisation fiche pec \\cpcapd2burv2.zcam.ztech\cap10burs\dab - abp - car\equip\03- apporter notre expertise aux crb\réclamations\00 - fiche pec\fiche délégation prise en charge vierge.docm rédiger la fiche pec , l’ enregistrer sous pec pole lien ci-dessous , la présenter et la faire signer par le délégataire ou l’ envoyer via ave pour qu’ elle soit signée par le délégataire de la cr " s:\dab - abp - car\equip\03 - process\05 - réclamations\la charte ave réclamations.pptx « envoyer la fiche pec à l’ usp par mail pour saisie de l’ opération comptable et archivage : impayespacifica@ca-bretagne.fr alimenter l’ ave par un commentaire en indiquant que la pec sera versée d’ ici quelques jours sur le compte client . organigramme satisfaction clients cr822 responsable : laurence liscouet chargés qualité : lydie decruz 8223333 melanie piednoir 822 3933 gwenaëlle caigneaux 822 3379 marina guerif 8223140 organigramme ecoute clients cr829 responsable : isabelle cueff chargés qualité : florence delaloy 829 0680 arnaud le boedec 829 0496 organigramme qualité et satisfaction clients cr836 responsable : benoit eucheloup pôle amélioration continue : pôle écoute clients : berengere poulain 8363542 		  sophie dennequin 836 3724 fabrice guillemin 836 3432 laetitia josse 836 3874 sophie bonniou 8363809 angélique desouches 836 3695 rozenn briens 8363369 pôle sav réseau : anne mailleux 836 3929 transfert au pôle ecoute ou sav en fonction de l’ origine organigramme ecoute clients cr860 responsable : françoise gueguen talmon chargés qualité : catherine lagarrosse 8607566 fanny le beller 8607610 marine le bris 8607550 caroline mauffret 8607601 nathalie serre 8607596 les ugs une implantation nationale au cœur des territoires 21 ugs 13 iard + 1 5 ugs pj + 1 3 ugs spécialisées dsin organigramme dsin 10 - 2021 - 6 ugs pj : rouen , aix en pce , rennes , bordeaux , caen , grenoble - pôle technique - rtn iard pro / corp / rc/ auto / nh - partenariats fraude 3 ugrs spécialisées montpellier – saint etienne - poitiers récolte , garantie locative , atm , entreprise et gestions externalisées 7 ugs iard : clermont fd , rennes , orléans , poitiers , metz , arras , la roche s/ yon 7 ugs iard : rouen , lyon , pau , montpellier , aix , strasbourg , dijon activités : - moa - pilotage - statistiques - planification activités : - budget - audit et projets - effectifs opérat . - logistique - communication format adresse mail : prénom.nom@ca-pacifica.fr dsin – pôle iard 1 s05 rennes s04 clermont s07 orléans s08 poitiers s09 metz s12 arras s13 lr/ yon pacifica – ugs de rennes 14 juin 2023 dsin – pôle iard 2 s01 rouen s02 lyon s03 pau s11 strasbourg s06 montpellier s10 aix dijon en 2023 pacifica – ugs de rennes 14 juin 2023 dsin – pôle pj pacifica – ugs de rennes 14 juin 2023 aix pj bordeaux rennes pj rouen pj caen 6ème pj à grenoble ouverture en septembre pôle rtn dsin – pôle activites specialisees pacifica – ugs de rennes 14 juin 2023 ugse poitiers sr1 montpellier saint etienne sr2 annuaire ugs sinistres annuaire ugs pj et ugrs annuaire assistance coordonnees utiles service telephone mail ugs 0800 810 812 gestionsinistre01@pacifica.fr ref sinistre en objet gestion des sinistres agri adresse générale gestionsr1@pacifica.fr europ assistance clientservices@europ-assistance.fr service consommateur pck ugpciereclamationsclients@ca-pacifica.fr atm 09 70 80 92 81 reclamations-crca-lcl@spb.eu pj 0800 813 810 pj@pacifica.fr ref sinistre en objet ugp cie pro 0810 20 25 20 ugpciepro@ca-pacifica.fr ugp cie part 0810 20 25 20 ugpciepart@ca-pacifica.fr departeme nt sante 09 77 40 50 00 infosante@departement-santé.com ugr 0800 810 816 ugr@ca-pacifica.fr specifica / finaxy 0801 907 762 gestion-part1@ca-specifica.fr

## Chunking

Several technics to chunk documents
- tokens chunking
- semantic chunking
...

In [4]:
# 1. Configuration
class Config:
    MODEL_NAME = 'all-MiniLM-L6-v2'  # Modèle BERT léger
    CHUNK_SIZE = 256                 # Taille des chunks en tokens
    CHUNK_OVERLAP = 48               # Chevauchement entre chunks
    INDEX_FILE = "document_index.faiss"
    METADATA_FILE = "metadata.json"
    DOCUMENTS_DIR = "cleaned_docs"   # Dossier contenant vos documents nettoyés

# 3. Découpeur de texte
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=Config.CHUNK_SIZE,
    chunk_overlap=Config.CHUNK_OVERLAP,
    length_function=len
)

@np.vectorize
def light_cleaning(document):
    ''' light cleaning for embedding '''
    document = document.replace('«', ' ').replace('»', ' ').replace('>', ' ').replace('<', ' ')
    document = document.replace('-', ' ').replace('+', ' ').replace('=', ' ').replace("n°", ' ')
    document = document.replace(':', ' ').replace(',', ' ').replace('.', ' ')
    document = document.replace('€', ' ')
    # Remove non-breaking spaces
    document = document.replace("\xa0", ' ')
    document = re.sub(r" +", ' ', document).strip()
    return document

# Cleaning the documents
cleaned_documents = light_cleaning(documents)
print(type(cleaned_documents), type(cleaned_documents.item(0)))

n_doc = 3
document = cleaned_documents[n_doc]
print(titles[n_doc])
print(document)

chunks = text_splitter.split_text(document.item(0))
print("\nCHUNKS:")
for chunk in chunks:
    print(" - ", chunk)

<class 'numpy.ndarray'> <class 'str'>
automatisation des impayés
automatisation des impayes procédure à utiliser après analyse de la cf01 et cf04 et cf02 si nécessaire utilisation se connecter au pvm de la cr concernée par l’impayé à régulariser compléter le fichier trame impayés tc01 le fichier se trouve sous s \dab abp car\equip\02 gerer les contrats de la souscription à la résiliation impayés \automatisation des impayes\trame impayes tc01 attention dans les pvm autre que la 22 le fichier se trouve sous s \dab abp car\equip\02 gerer les contrats de la souscription à la résiliation impayés \automatisation des impayes\trame impayes tc01 a noter que l’intêret de satambo est de remplir le fichier excel avec plusieurs impayés de clients différents et de toutes cr le but étant de traiter en masse attention fichier a remplir en majuscules ne compléter que l’onglet impayés colonne a numéro de compte client colonne b nom et prénom du client colonne c montant impayé avec frais du contrat à régulariser à débiter du compte client attention utiliser la virgule et pas le point pour les centimes colonne d montant impayé sans les frais du contrat à régulariser attention utiliser la virgule et pas le point pour les centimes colonne e cr 22 29 56 ou 35 colonne f numéro du contrat sans le 907 colonne g nom du contrat colonne h type à ne renseigner que s’il s’agit d’une régularisation par chèque sinon ne rien indiquer colonne i ne rien renseigner résultat du satambo si ok action correctement effectuée si erreur le message d’erreur apparaitra dans cette colonne il faudra alors agir manuellement traitement impayé manuel colonne j noter pro ou part 4 cas de figure possible régularisation par prélèvement avec frais excel tc01 montant avec frais montant sans frais exemple de saisie régularisation par prélèvement sans frais excel tc01 montant sans frais montant sans frais exemple de saisie régularisation par chèque avec frais excel tc01 5 00 noter cheque exemple de saisie régularisation par chèque sans frais excel tc01 une fois le fichier excel complété cliquer sur enregistrer puis fermer le fichier excel important une ligne par contrat par exemple s’il y a 5 contrats à régulariser pour le même client il faudra alors noter les 5 contrats 1 contrat par ligne donc 5 lignes 3 scripts satambo à utiliser satambo tc01 satambo cf01 satambo ev01 lancer le satambo impayé tc01 le script satambo tc01 doit être lancé sur le pvm de la cr concernée au préalable se connecter au 3270 du pvm et rester sur la page menu ci dessous important pour pouvoir lancer le satambo dans menu windows démarrer choisir logiciels métiers satambo une fois le satambo ouvert cliquer sur production traitement de requêtes à la demande choisir tc01 impayes double cliquer dessus il apparait alors dans la fenêtre en dessous se positionner dessus et cliquer sur la flèche verte sélectionner le fichier excel tc01 préalablement rempli qui se trouve sous s \dab abp car\equip\02 gerer les contrats de la souscription à la résiliation impayés \automatisation des impayes\trame impayes tc01 en cliquant sur ok sélectionner le fichier excel trame impayés tc01 une fois le fichier excel sélectionné afficher le 3270 pour vérifier que les transactions se déroulent correctement le satambo s’exécute compléter le fichier trame impayé cf01 a noter que l’intêret de satambo est de remplir le fichier excel avec plusieurs impayés de clients différents et de toutes cr le but étant de traiter en masse attention fichier a remplir en majuscules revenir sur le pvm de la cr22 ouvrir le fichier trame impayé cf01 qui se trouve sous s \dab abp car\equip\02 gerer les contrats de la souscription à la résiliation impayés \automatisation des impayes\trame impayes tc01 excel cf01 colonne a numéro de contrat entier colonne b numéro de contrat sans le 907 colonne c montant impayé sans les frais du contrat à régulariser attention utiliser la virgule et pas le point colonne d noter libellé ev01 selon le modèle suivant reg nh rsl ou med 26 90 5 frais osd 560221 colonne e ne rien renseigner résultat du satambo si ok encaissement pris en compte sur règlement si erreur le message d’erreur apparaitra dans cette colonne colonne f noter pro ou part exemple de saisie une fois le fichier excel complété cliquer sur enregistrer puis fermer le fichier excel important une ligne par contrat par exemple s’il y a 5 contrats à régulariser pour le même client il faudra alors noter les 5 contrats 1 contrat par ligne donc 5 lignes lancer le satambo impayé cf01 au préalable se connecter au 3270 du pvm cr22 et rester sur la page menu ci dessous important pour pouvoir lancer le satambo pour pouvoir sélectionner le nouveau script satambo il faut enlever le script précédent qui se trouve dans exécution et résultats en cliquant dessus et en appuyant sur la feuille blanche lancer le satambo impayé cf01 supprimer le point d’interrogation et saisir son identifiant de connexion au 3270 supprimer le point d’interrogation et saisir son mot de passe de connexion au 3270 sélectionner le fichier excel impayés cf01 préalablement rempli en cliquant sur ok sélectionner le fichier excel trame impayés cf01 une fois le fichier excel sélectionné afficher le 3270 pour vérifier que les transactions se déroulent correctement le satambo s’exécute lancer le satambo impayé ev01 au préalable se connecter au 3270 du pvm cr22 et rester sur la page menu ci dessous important pour pouvoir lancer le satambo pour pouvoir sélectionner le nouveau script satambo il faut enlever le script précédent qui se trouve dans exécution et résultats en cliquant dessus et en appuyant sur la feuille blanche lancer le satambo impayé ev01 supprimer le point d’interrogation et saisir son identifiant de connexion au 3270 supprimer le point d’interrogation et saisir son mot de passe de connexion au 3270 sélectionner le fichier excel impayés cf01 et ev01 préalablement rempli en cliquant sur ok sélectionner le fichier excel trame impayés cf01 une fois le fichier excel sélectionné afficher le 3270 pour vérifier que les transactions se déroulent correctement le satambo s’exécute une fois les opérations terminées merci d’enregistrer les fichiers excel dans s \dab abp car\equip\02 gerer les contrats de la souscription a la resiliation\impayes\pacifica\impayes 2020 vous enregistrez les tableaux dans le dossier de la cr concernée après avoir créé un sous dossier avec la date du jour remplace les impressions d’écrans que nous faisions quand nous passions manuellement les opérations lors d’une régularisation par chèque merci de faire une copie des chèques reçus que vous archiverez dans la journée avec les copies d’écrans que vous avez utilisées pour votre analyse important une fois le satambo terminé il faut supprimer toutes les écritures des fichiers excel tc01 et cf01 avant de relancer un nouveau script sinon les écritures passeront deux fois suivi du traitement des impayés il ne sera plus nécessaire de compléter le tableau des impayés actuel un suivi automatique est effectué il se trouve sous le lien suivant http //ybp10 iucrprdapa ca technologies fr 81/ppb/ejed/ un suivi est disponible pour la cf01 et pour la tc01 avec possibilité de filtrer par date

CHUNKS:
 -  automatisation des impayes procédure à utiliser après analyse de la cf01 et cf04 et cf02 si nécessaire utilisation se connecter au pvm de la cr concernée par l’impayé à régulariser compléter le fichier trame impayés tc01 le fichier se trouve sous s \dab
 -  impayés tc01 le fichier se trouve sous s \dab abp car\equip\02 gerer les contrats de la souscription à la résiliation impayés \automatisation des impayes\trame impayes tc01 attention dans les pvm autre que la 22 le fichier se trouve sous s \dab abp
 -  que la 22 le fichier se trouve sous s \dab abp car\equip\02 gerer les contrats de la souscription à la résiliation impayés \automatisation des impayes\trame impayes tc01 a noter que l’intêret de satambo est de remplir le fichier excel avec plusieurs
 -  est de remplir le fichier excel avec plusieurs impayés de clients différents et de toutes cr le but étant de traiter en masse attention fichier a remplir en majuscules ne compléter que l’onglet impayés colonne a numéro de compte client colonne b nom et
 -  a numéro de compte client colonne b nom et prénom du client colonne c montant impayé avec frais du contrat à régulariser à débiter du compte client attention utiliser la virgule et pas le point pour les centimes colonne d montant impayé sans les frais du
 -  colonne d montant impayé sans les frais du contrat à régulariser attention utiliser la virgule et pas le point pour les centimes colonne e cr 22 29 56 ou 35 colonne f numéro du contrat sans le 907 colonne g nom du contrat colonne h type à ne renseigner
 -  g nom du contrat colonne h type à ne renseigner que s’il s’agit d’une régularisation par chèque sinon ne rien indiquer colonne i ne rien renseigner résultat du satambo si ok action correctement effectuée si erreur le message d’erreur apparaitra dans cette
 -  le message d’erreur apparaitra dans cette colonne il faudra alors agir manuellement traitement impayé manuel colonne j noter pro ou part 4 cas de figure possible régularisation par prélèvement avec frais excel tc01 montant avec frais montant sans frais
 -  tc01 montant avec frais montant sans frais exemple de saisie régularisation par prélèvement sans frais excel tc01 montant sans frais montant sans frais exemple de saisie régularisation par chèque avec frais excel tc01 5 00 noter cheque exemple de saisie
 -  excel tc01 5 00 noter cheque exemple de saisie régularisation par chèque sans frais excel tc01 une fois le fichier excel complété cliquer sur enregistrer puis fermer le fichier excel important une ligne par contrat par exemple s’il y a 5 contrats à
 -  par contrat par exemple s’il y a 5 contrats à régulariser pour le même client il faudra alors noter les 5 contrats 1 contrat par ligne donc 5 lignes 3 scripts satambo à utiliser satambo tc01 satambo cf01 satambo ev01 lancer le satambo impayé tc01 le
 -  satambo ev01 lancer le satambo impayé tc01 le script satambo tc01 doit être lancé sur le pvm de la cr concernée au préalable se connecter au 3270 du pvm et rester sur la page menu ci dessous important pour pouvoir lancer le satambo dans menu windows
 -  pouvoir lancer le satambo dans menu windows démarrer choisir logiciels métiers satambo une fois le satambo ouvert cliquer sur production traitement de requêtes à la demande choisir tc01 impayes double cliquer dessus il apparait alors dans la fenêtre en
 -  dessus il apparait alors dans la fenêtre en dessous se positionner dessus et cliquer sur la flèche verte sélectionner le fichier excel tc01 préalablement rempli qui se trouve sous s \dab abp car\equip\02 gerer les contrats de la souscription à la
 -  gerer les contrats de la souscription à la résiliation impayés \automatisation des impayes\trame impayes tc01 en cliquant sur ok sélectionner le fichier excel trame impayés tc01 une fois le fichier excel sélectionné afficher le 3270 pour vérifier que les
 -  afficher le 3270 pour vérifier que les transactions se déroulent correctement le satambo s’exécute compléter le fichier trame impayé cf01 a noter que l’intêret de satambo est de remplir le fichier excel avec plusieurs impayés de clients différents et de
 -  plusieurs impayés de clients différents et de toutes cr le but étant de traiter en masse attention fichier a remplir en majuscules revenir sur le pvm de la cr22 ouvrir le fichier trame impayé cf01 qui se trouve sous s \dab abp car\equip\02 gerer les
 -  trouve sous s \dab abp car\equip\02 gerer les contrats de la souscription à la résiliation impayés \automatisation des impayes\trame impayes tc01 excel cf01 colonne a numéro de contrat entier colonne b numéro de contrat sans le 907 colonne c montant
 -  numéro de contrat sans le 907 colonne c montant impayé sans les frais du contrat à régulariser attention utiliser la virgule et pas le point colonne d noter libellé ev01 selon le modèle suivant reg nh rsl ou med 26 90 5 frais osd 560221 colonne e ne rien
 -  med 26 90 5 frais osd 560221 colonne e ne rien renseigner résultat du satambo si ok encaissement pris en compte sur règlement si erreur le message d’erreur apparaitra dans cette colonne colonne f noter pro ou part exemple de saisie une fois le fichier
 -  ou part exemple de saisie une fois le fichier excel complété cliquer sur enregistrer puis fermer le fichier excel important une ligne par contrat par exemple s’il y a 5 contrats à régulariser pour le même client il faudra alors noter les 5 contrats 1
 -  client il faudra alors noter les 5 contrats 1 contrat par ligne donc 5 lignes lancer le satambo impayé cf01 au préalable se connecter au 3270 du pvm cr22 et rester sur la page menu ci dessous important pour pouvoir lancer le satambo pour pouvoir
 -  pour pouvoir lancer le satambo pour pouvoir sélectionner le nouveau script satambo il faut enlever le script précédent qui se trouve dans exécution et résultats en cliquant dessus et en appuyant sur la feuille blanche lancer le satambo impayé cf01
 -  feuille blanche lancer le satambo impayé cf01 supprimer le point d’interrogation et saisir son identifiant de connexion au 3270 supprimer le point d’interrogation et saisir son mot de passe de connexion au 3270 sélectionner le fichier excel impayés cf01
 -  3270 sélectionner le fichier excel impayés cf01 préalablement rempli en cliquant sur ok sélectionner le fichier excel trame impayés cf01 une fois le fichier excel sélectionné afficher le 3270 pour vérifier que les transactions se déroulent correctement le
 -  les transactions se déroulent correctement le satambo s’exécute lancer le satambo impayé ev01 au préalable se connecter au 3270 du pvm cr22 et rester sur la page menu ci dessous important pour pouvoir lancer le satambo pour pouvoir sélectionner le nouveau
 -  le satambo pour pouvoir sélectionner le nouveau script satambo il faut enlever le script précédent qui se trouve dans exécution et résultats en cliquant dessus et en appuyant sur la feuille blanche lancer le satambo impayé ev01 supprimer le point
 -  le satambo impayé ev01 supprimer le point d’interrogation et saisir son identifiant de connexion au 3270 supprimer le point d’interrogation et saisir son mot de passe de connexion au 3270 sélectionner le fichier excel impayés cf01 et ev01 préalablement
 -  excel impayés cf01 et ev01 préalablement rempli en cliquant sur ok sélectionner le fichier excel trame impayés cf01 une fois le fichier excel sélectionné afficher le 3270 pour vérifier que les transactions se déroulent correctement le satambo s’exécute
 -  se déroulent correctement le satambo s’exécute une fois les opérations terminées merci d’enregistrer les fichiers excel dans s \dab abp car\equip\02 gerer les contrats de la souscription a la resiliation\impayes\pacifica\impayes 2020 vous enregistrez les
 -  2020 vous enregistrez les tableaux dans le dossier de la cr concernée après avoir créé un sous dossier avec la date du jour remplace les impressions d’écrans que nous faisions quand nous passions manuellement les opérations lors d’une régularisation par
 -  les opérations lors d’une régularisation par chèque merci de faire une copie des chèques reçus que vous archiverez dans la journée avec les copies d’écrans que vous avez utilisées pour votre analyse important une fois le satambo terminé il faut supprimer
 -  une fois le satambo terminé il faut supprimer toutes les écritures des fichiers excel tc01 et cf01 avant de relancer un nouveau script sinon les écritures passeront deux fois suivi du traitement des impayés il ne sera plus nécessaire de compléter le
 -  il ne sera plus nécessaire de compléter le tableau des impayés actuel un suivi automatique est effectué il se trouve sous le lien suivant http //ybp10 iucrprdapa ca technologies fr 81/ppb/ejed/ un suivi est disponible pour la cf01 et pour la tc01 avec
 -  disponible pour la cf01 et pour la tc01 avec possibilité de filtrer par date

**Benchmark vectorization**

In [237]:
%timeit light_cleaning(cleaned_documents)
%timeit [light_cleaning(doc) for doc in cleaned_documents]
%timeit map(light_cleaning, cleaned_documents)

3.11 ms ± 59.8 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
5.33 ms ± 76.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
49.8 ns ± 0.616 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

**Test vectorisation**

In [5]:
for chunk in chunks:
    print("nb tokens:", len(nlp(chunk)))

nb tokens: 44
nb tokens: 42
nb tokens: 42
nb tokens: 45
nb tokens: 46
nb tokens: 49
nb tokens: 46
nb tokens: 40
nb tokens: 40
nb tokens: 44
nb tokens: 47
nb tokens: 46
nb tokens: 39
nb tokens: 41
nb tokens: 39
nb tokens: 42
nb tokens: 45
nb tokens: 40
nb tokens: 49
nb tokens: 46
nb tokens: 46
nb tokens: 45
nb tokens: 40
nb tokens: 41
nb tokens: 38
nb tokens: 42
nb tokens: 40
nb tokens: 41
nb tokens: 39
nb tokens: 36
nb tokens: 42
nb tokens: 43
nb tokens: 42
nb tokens: 47
nb tokens: 14

## Sentence-camembert-large

In [6]:
# https://datacorner.fr/document-chunking/
from langchain_huggingface import HuggingFaceEmbeddings

# hf_embedding = HuggingFaceEmbeddings(model)

**Locally load the model**

In [7]:
model = SentenceTransformer(r"C:\Users\S589669\Documents\DEV\ABP-Doctheque\sentence-camembert-large", local_files_only=True)
model.encode("Hello")

array([ 0.29252246,  0.02982062, -0.10471618, ...,  0.22709577,
        0.05306111, -0.58324724], shape=(1024,), dtype=float32)

In [ ]:
# Documents are too long (need to be chunked)
n_index = 0
print("max_seq_length", model.max_seq_length)
model.max_seq_length = 1024
print("max_seq_length", model.max_seq_length)
# document = ["Procédure Historique des modifications Table des matières Contenu Description du processus Contexte Action à mener lorsque le partenaire est déjà connu dans la base sous une autre référence ce qui", 'Procédure Rajout codes promo si oubli conseiller Rôle Nom Prénom Rédaction HAMON Joel Contribution XXXXX Validation XXXXX Historique des modifications Validation Version Date Rôle']

print("len documents", len(documents[n_index]))
corpus_embeddings = model.encode(documents[n_index], convert_to_numpy=True)
print("Shape: ", corpus_embeddings.shape)
corpus_embeddings

**Documents chunking**

In [ ]:
chunks = []
# Indexes_documents sert de mapping entre les chunks et les documents d'origine
indexes_documents = []

for i, document in enumerate(cleaned_documents):
    chunks_ = text_splitter.split_text(document)
    chunks.extend(chunks_)
    indexes_documents.extend([i] * len(chunks_))

print('Documents length:')
for i, document in enumerate(cleaned_documents):
    print(f"nb tokens: {len(nlp(document.item(0)))}\t nb chunks: {indexes_documents.count(i)}")
print(f"nb total chunks: {len(indexes_documents)}")

print("\nCHUNKS:")
for i, chunk in enumerate(chunks):
    print(f"{indexes_documents[i]} - {chunk}")

Documents length:
nb tokens: 1170	 nb chunks: 36
nb tokens: 23	 nb chunks: 1
nb tokens: 180	 nb chunks: 5
nb tokens: 1198	 nb chunks: 35
nb tokens: 135	 nb chunks: 4
nb tokens: 159	 nb chunks: 5
nb tokens: 2746	 nb chunks: 71
nb tokens: 2427	 nb chunks: 65
nb tokens: 966	 nb chunks: 26
nb tokens: 43	 nb chunks: 2
nb tokens: 793	 nb chunks: 22
nb tokens: 616	 nb chunks: 18
nb tokens: 1062	 nb chunks: 29
nb tokens: 378	 nb chunks: 10
nb tokens: 819	 nb chunks: 24
nb tokens: 517	 nb chunks: 16
nb tokens: 92	 nb chunks: 3
nb tokens: 224	 nb chunks: 6
nb total chunks: 378

CHUNKS:
0 - gestion des reclamations organisation car animation et coordination journalière avec répartition des réclamations une équipe polyvalente de 18 conseillers qui traite les réclamations des journées dédiées et un suivi personnel des réclamations prises en
0 - un suivi personnel des réclamations prises en charge veille permanente sur les réclamations en cours/suivi par binôme si absence une boîte mail dédiée aux réclamations sommaire contexte objectifs detail de la procedure demandes de renseignements
0 - de la procedure demandes de renseignements assistance car conversation à trois réclamations analyse décision /pec regularisation rédaction de la fiche pec envoi à usp pour traitement annexes organigramme écoute client par cr annuaire ugs coordonnées
0 - écoute client par cr annuaire ugs coordonnées utiles contexte car est en charge du traitement des demandes de renseignements et des réclamations clients sur le périmètre iard part et pro et sur la prévoyance part et pro objectifs traitement en amont des
0 - part et pro objectifs traitement en amont des demandes de renseignements en soutien des conseillers traitement des réclamations saisies en ave by caesar en recherchant la satisfaction client final et conseiller crb rechercher des solutions gagnant gagnant
0 - crb rechercher des solutions gagnant gagnant detail de la procedure demandes de renseignements prélèvements des cotisations problématiques de résiliations non saisies ou refusées proposition de conversation à trois client/conseiller/ugs afin de déterminer
0 - trois client/conseiller/ugs afin de déterminer si la question relève d’une explication ou d’une réclamation test en cours de validation filtre service écoute qui propose au conseiller de nous appeler pour l’accompagner dans la recherche d’explication avec
0 - dans la recherche d’explication avec possibilité de conversation à trois client/conseiller/car test en cours de validation questions liées à l’assistance à la gestion des sinistres les mots pour le dire detail de la procedure réclamations tout courrier de
0 - de la procedure réclamations tout courrier de réclamation client adressé au pôle doit être saisie immédiatement et l’accusé réception envoyé au client tamponné et signé toute réclamation doit être prise en charge dans les 2 jours ouvrés suivant son
0 - en charge dans les 2 jours ouvrés suivant son enregistrement analyse vérifier le bien fondé de la réclamation erreur ca dysfonctionnement défaut de conseil apporter des explications claires et précises proposer une prise en charge commerciale à leur
0 - proposer une prise en charge commerciale à leur niveau si justifiée pour préserver la relation client apporter des explications claires et précises pour faciliter les réponses des conseillers et services écoute et expliquer les calculs si pec en l’absence
0 - et expliquer les calculs si pec en l’absence d’erreur ca retour au conseiller et/ou service écoute en indiquant que le pôle ne prend pas en charge detail de la procedure réclamations tableaux de suivi individuel à votre disposition s \dab abp car\equip\03
0 - à votre disposition s \dab abp car\equip\03 apporter notre expertise aux crb\tableaux individuels suivi reclamations en cours régularisation décision/prise en charge la décision de prise en charge financière appartient à chaque cr délégation au pôle
0 - appartient à chaque cr délégation au pôle jusqu’à 1000 responsable pôle 1000 responsable unité 500 animateur –analyste 300 au delà de 1000 si réclamation arrivant en direct du conseiller transférer la demande de pec à mon ru qui fera suivre au délégataire
0 - de pec à mon ru qui fera suivre au délégataire de la cr réclamation arrivant en groupe de discussion via service écoute client transférer la demande de pec dans l’ave afin que le service écoute la fasse signer par le délégataire de la cr exception en cr22
0 - par le délégataire de la cr exception en cr22 où il faut envoyer la fiche au ru pour décision alexandre blanchard préconiser la rétroactivité de deux ans validée par le service juridique responsabiliser le client qui a tardé à nous signaler une erreur un
0 - qui a tardé à nous signaler une erreur un doublon alors qu’il est prélevé et reçoit des documents tous les ans l’invitant à vérifier la conformité de son contrat et à nous signaler tout changement concernant le risque assuré solution gagnant/gagnant sauf
0 - le risque assuré solution gagnant/gagnant sauf dans les cas de dossier de succession partiellement traité si c’est le client et non le conseiller qui réclame et qu’il y a bien erreur ca la prise en charge devra alors être totale régularisation fiche pec
0 - alors être totale régularisation fiche pec \\cpcapd2burv2 zcam ztech\cap10burs\dab abp car\equip\03 apporter notre expertise aux crb\réclamations\00 fiche pec\fiche délégation prise en charge vierge docm rédiger la fiche pec l’enregistrer sous pec pole
0 - la fiche pec l’enregistrer sous pec pole lien ci dessous la présenter et la faire signer par le délégataire ou l’envoyer via ave pour qu’elle soit signée par le délégataire de la cr "s \dab abp car\equip\03 process\05 réclamations\la charte ave
0 - process\05 réclamations\la charte ave réclamations pptx envoyer la fiche pec à l’usp par mail pour saisie de l’opération comptable et archivage impayespacifica@ca bretagne fr alimenter l’ave par un commentaire en indiquant que la pec sera versée d’ici
0 - en indiquant que la pec sera versée d’ici quelques jours sur le compte client organigramme satisfaction clients cr822 responsable laurence liscouet chargés qualité lydie decruz 8223333 melanie piednoir 822 3933 gwenaëlle caigneaux 822 3379 marina guerif
0 - 3933 gwenaëlle caigneaux 822 3379 marina guerif 8223140 organigramme ecoute clients cr829 responsable isabelle cueff chargés qualité florence delaloy 829 0680 arnaud le boedec 829 0496 organigramme qualité et satisfaction clients cr836 responsable benoit
0 - satisfaction clients cr836 responsable benoit eucheloup pôle amélioration continue pôle écoute clients berengere poulain 8363542 		 sophie dennequin 836 3724 fabrice guillemin 836 3432 laetitia josse 836 3874 sophie bonniou 8363809 angélique desouches 836
0 - sophie bonniou 8363809 angélique desouches 836 3695 rozenn briens 8363369 pôle sav réseau anne mailleux 836 3929 transfert au pôle ecoute ou sav en fonction de l’origine organigramme ecoute clients cr860 responsable françoise gueguen talmon chargés
0 - responsable françoise gueguen talmon chargés qualité catherine lagarrosse 8607566 fanny le beller 8607610 marine le bris 8607550 caroline mauffret 8607601 nathalie serre 8607596 les ugs une implantation nationale au cœur des territoires 21 ugs 13 iard 1 5
0 - au cœur des territoires 21 ugs 13 iard 1 5 ugs pj 1 3 ugs spécialisées dsin organigramme dsin 10 2021 6 ugs pj rouen aix en pce rennes bordeaux caen grenoble pôle technique rtn iard pro/corp/rc/ auto/nh partenariats fraude 3 ugrs spécialisées montpellier
0 - fraude 3 ugrs spécialisées montpellier – saint etienne poitiers récolte garantie locative atm entreprise et gestions externalisées 7 ugs iard clermont fd rennes orléans poitiers metz arras la roche s/ yon 7 ugs iard rouen lyon pau montpellier aix
0 - yon 7 ugs iard rouen lyon pau montpellier aix strasbourg dijon activités moa pilotage statistiques planification activités budget audit et projets effectifs opérat logistique communication format adresse mail prénom nom@ca pacifica fr dsin – pôle iard 1
0 - prénom nom@ca pacifica fr dsin – pôle iard 1 s05 rennes s04 clermont s07 orléans s08 poitiers s09 metz s12 arras s13 lr/ yon pacifica – ugs de rennes 14 juin 2023 dsin – pôle iard 2 s01 rouen s02 lyon s03 pau s11 strasbourg s06 montpellier s10 aix dijon
0 - s11 strasbourg s06 montpellier s10 aix dijon en 2023 pacifica – ugs de rennes 14 juin 2023 dsin – pôle pj pacifica – ugs de rennes 14 juin 2023 aix pj bordeaux rennes pj rouen pj caen 6ème pj à grenoble ouverture en septembre pôle rtn dsin – pôle
0 - ouverture en septembre pôle rtn dsin – pôle activites specialisees pacifica – ugs de rennes 14 juin 2023 ugse poitiers sr1 montpellier saint etienne sr2 annuaire ugs sinistres annuaire ugs pj et ugrs annuaire assistance coordonnees utiles service
0 - annuaire assistance coordonnees utiles service telephone mail ugs 0800 810 812 gestionsinistre01@pacifica fr ref sinistre en objet gestion des sinistres agri adresse générale gestionsr1@pacifica fr europ assistance clientservices@europ assistance fr
0 - assistance clientservices@europ assistance fr service consommateur pck ugpciereclamationsclients@ca pacifica fr atm 09 70 80 92 81 reclamations crca lcl@spb eu pj 0800 813 810 pj@pacifica fr ref sinistre en objet ugp cie pro 0810 20 25 20 ugpciepro@ca
0 - en objet ugp cie pro 0810 20 25 20 ugpciepro@ca pacifica fr ugp cie part 0810 20 25 20 ugpciepart@ca pacifica fr departeme nt sante 09 77 40 50 00 infosante@departement santé com ugr 0800 810 816 ugr@ca pacifica fr specifica/finaxy 0801 907 762 gestion
0 - fr specifica/finaxy 0801 907 762 gestion part1@ca specifica fr
1 - aav dérogations d08 d10 délégation équipe car délégation animateur analyste ru à indiquer dans le commentaire à la validation maj 04 03 2024
2 - faire la cf04 avec la référence bancaire pour vérifier si paiements en retard on régularise l’ensemble des impayés analyser les impayes suite a osd et en regularisation 1 le contrat est résilié pour impayé 3 le contrat est en med 2 le contrat est en cours
2 - le contrat est en med 2 le contrat est en cours avec une dette antérieure si le montant indiqué en cf04 est à 3 mois de cotisation 5 de frais j e récupère 3 mois de cotisation 5 de frais je récupère le montant indiqué en cf04 on ne prélève pas de frais je
2 - indiqué en cf04 on ne prélève pas de frais je récupère le montant indiqué en cf04 avec les frais faire une cf02 avec la référence bancaire distributeur de cr et indiquer 00 pour le mode de règlement pour vérifier si des règlements manuels ont déjà été
2 - vérifier si des règlements manuels ont déjà été effectués faire une cf01 sur le contrat en impayé pour vérifier le motif du rejet je me mets sur la cotisation qui a été rejetée si le motif du rejet est ac06 opposition sur prélèvement demander au collègue
2 - opposition sur prélèvement demander au collègue d’agence de lever l’opposition et de nous renvoyer un osd pour demander la régularisation
3 - automatisation des impayes procédure à utiliser après analyse de la cf01 et cf04 et cf02 si nécessaire utilisation se connecter au pvm de la cr concernée par l’impayé à régulariser compléter le fichier trame impayés tc01 le fichier se trouve sous s \dab
3 - impayés tc01 le fichier se trouve sous s \dab abp car\equip\02 gerer les contrats de la souscription à la résiliation impayés \automatisation des impayes\trame impayes tc01 attention dans les pvm autre que la 22 le fichier se trouve sous s \dab abp
3 - que la 22 le fichier se trouve sous s \dab abp car\equip\02 gerer les contrats de la souscription à la résiliation impayés \automatisation des impayes\trame impayes tc01 a noter que l’intêret de satambo est de remplir le fichier excel avec plusieurs
3 - est de remplir le fichier excel avec plusieurs impayés de clients différents et de toutes cr le but étant de traiter en masse attention fichier a remplir en majuscules ne compléter que l’onglet impayés colonne a numéro de compte client colonne b nom et
3 - a numéro de compte client colonne b nom et prénom du client colonne c montant impayé avec frais du contrat à régulariser à débiter du compte client attention utiliser la virgule et pas le point pour les centimes colonne d montant impayé sans les frais du
3 - colonne d montant impayé sans les frais du contrat à régulariser attention utiliser la virgule et pas le point pour les centimes colonne e cr 22 29 56 ou 35 colonne f numéro du contrat sans le 907 colonne g nom du contrat colonne h type à ne renseigner
3 - g nom du contrat colonne h type à ne renseigner que s’il s’agit d’une régularisation par chèque sinon ne rien indiquer colonne i ne rien renseigner résultat du satambo si ok action correctement effectuée si erreur le message d’erreur apparaitra dans cette
3 - le message d’erreur apparaitra dans cette colonne il faudra alors agir manuellement traitement impayé manuel colonne j noter pro ou part 4 cas de figure possible régularisation par prélèvement avec frais excel tc01 montant avec frais montant sans frais
3 - tc01 montant avec frais montant sans frais exemple de saisie régularisation par prélèvement sans frais excel tc01 montant sans frais montant sans frais exemple de saisie régularisation par chèque avec frais excel tc01 5 00 noter cheque exemple de saisie
3 - excel tc01 5 00 noter cheque exemple de saisie régularisation par chèque sans frais excel tc01 une fois le fichier excel complété cliquer sur enregistrer puis fermer le fichier excel important une ligne par contrat par exemple s’il y a 5 contrats à
3 - par contrat par exemple s’il y a 5 contrats à régulariser pour le même client il faudra alors noter les 5 contrats 1 contrat par ligne donc 5 lignes 3 scripts satambo à utiliser satambo tc01 satambo cf01 satambo ev01 lancer le satambo impayé tc01 le
3 - satambo ev01 lancer le satambo impayé tc01 le script satambo tc01 doit être lancé sur le pvm de la cr concernée au préalable se connecter au 3270 du pvm et rester sur la page menu ci dessous important pour pouvoir lancer le satambo dans menu windows
3 - pouvoir lancer le satambo dans menu windows démarrer choisir logiciels métiers satambo une fois le satambo ouvert cliquer sur production traitement de requêtes à la demande choisir tc01 impayes double cliquer dessus il apparait alors dans la fenêtre en
3 - dessus il apparait alors dans la fenêtre en dessous se positionner dessus et cliquer sur la flèche verte sélectionner le fichier excel tc01 préalablement rempli qui se trouve sous s \dab abp car\equip\02 gerer les contrats de la souscription à la
3 - gerer les contrats de la souscription à la résiliation impayés \automatisation des impayes\trame impayes tc01 en cliquant sur ok sélectionner le fichier excel trame impayés tc01 une fois le fichier excel sélectionné afficher le 3270 pour vérifier que les
3 - afficher le 3270 pour vérifier que les transactions se déroulent correctement le satambo s’exécute compléter le fichier trame impayé cf01 a noter que l’intêret de satambo est de remplir le fichier excel avec plusieurs impayés de clients différents et de
3 - plusieurs impayés de clients différents et de toutes cr le but étant de traiter en masse attention fichier a remplir en majuscules revenir sur le pvm de la cr22 ouvrir le fichier trame impayé cf01 qui se trouve sous s \dab abp car\equip\02 gerer les
3 - trouve sous s \dab abp car\equip\02 gerer les contrats de la souscription à la résiliation impayés \automatisation des impayes\trame impayes tc01 excel cf01 colonne a numéro de contrat entier colonne b numéro de contrat sans le 907 colonne c montant
3 - numéro de contrat sans le 907 colonne c montant impayé sans les frais du contrat à régulariser attention utiliser la virgule et pas le point colonne d noter libellé ev01 selon le modèle suivant reg nh rsl ou med 26 90 5 frais osd 560221 colonne e ne rien
3 - med 26 90 5 frais osd 560221 colonne e ne rien renseigner résultat du satambo si ok encaissement pris en compte sur règlement si erreur le message d’erreur apparaitra dans cette colonne colonne f noter pro ou part exemple de saisie une fois le fichier
3 - ou part exemple de saisie une fois le fichier excel complété cliquer sur enregistrer puis fermer le fichier excel important une ligne par contrat par exemple s’il y a 5 contrats à régulariser pour le même client il faudra alors noter les 5 contrats 1
3 - client il faudra alors noter les 5 contrats 1 contrat par ligne donc 5 lignes lancer le satambo impayé cf01 au préalable se connecter au 3270 du pvm cr22 et rester sur la page menu ci dessous important pour pouvoir lancer le satambo pour pouvoir
3 - pour pouvoir lancer le satambo pour pouvoir sélectionner le nouveau script satambo il faut enlever le script précédent qui se trouve dans exécution et résultats en cliquant dessus et en appuyant sur la feuille blanche lancer le satambo impayé cf01
3 - feuille blanche lancer le satambo impayé cf01 supprimer le point d’interrogation et saisir son identifiant de connexion au 3270 supprimer le point d’interrogation et saisir son mot de passe de connexion au 3270 sélectionner le fichier excel impayés cf01
3 - 3270 sélectionner le fichier excel impayés cf01 préalablement rempli en cliquant sur ok sélectionner le fichier excel trame impayés cf01 une fois le fichier excel sélectionné afficher le 3270 pour vérifier que les transactions se déroulent correctement le
3 - les transactions se déroulent correctement le satambo s’exécute lancer le satambo impayé ev01 au préalable se connecter au 3270 du pvm cr22 et rester sur la page menu ci dessous important pour pouvoir lancer le satambo pour pouvoir sélectionner le nouveau
3 - le satambo pour pouvoir sélectionner le nouveau script satambo il faut enlever le script précédent qui se trouve dans exécution et résultats en cliquant dessus et en appuyant sur la feuille blanche lancer le satambo impayé ev01 supprimer le point
3 - le satambo impayé ev01 supprimer le point d’interrogation et saisir son identifiant de connexion au 3270 supprimer le point d’interrogation et saisir son mot de passe de connexion au 3270 sélectionner le fichier excel impayés cf01 et ev01 préalablement
3 - excel impayés cf01 et ev01 préalablement rempli en cliquant sur ok sélectionner le fichier excel trame impayés cf01 une fois le fichier excel sélectionné afficher le 3270 pour vérifier que les transactions se déroulent correctement le satambo s’exécute
3 - se déroulent correctement le satambo s’exécute une fois les opérations terminées merci d’enregistrer les fichiers excel dans s \dab abp car\equip\02 gerer les contrats de la souscription a la resiliation\impayes\pacifica\impayes 2020 vous enregistrez les
3 - 2020 vous enregistrez les tableaux dans le dossier de la cr concernée après avoir créé un sous dossier avec la date du jour remplace les impressions d’écrans que nous faisions quand nous passions manuellement les opérations lors d’une régularisation par
3 - les opérations lors d’une régularisation par chèque merci de faire une copie des chèques reçus que vous archiverez dans la journée avec les copies d’écrans que vous avez utilisées pour votre analyse important une fois le satambo terminé il faut supprimer
3 - une fois le satambo terminé il faut supprimer toutes les écritures des fichiers excel tc01 et cf01 avant de relancer un nouveau script sinon les écritures passeront deux fois suivi du traitement des impayés il ne sera plus nécessaire de compléter le
3 - il ne sera plus nécessaire de compléter le tableau des impayés actuel un suivi automatique est effectué il se trouve sous le lien suivant http //ybp10 iucrprdapa ca technologies fr 81/ppb/ejed/ un suivi est disponible pour la cf01 et pour la tc01 avec
3 - disponible pour la cf01 et pour la tc01 avec possibilité de filtrer par date
4 - v/ 3 60 1 01 liste des reglements clients 822s506813 client 82200000081114473 sce societe civile d'exploitation ag contrat 2604940907 ma effet 01 01 2005 00h00 resilie le 28 01 2025 cotisation 2024 01/12/2024 813 90 soldee 01/11/2024 813 90 soldee

**Chunks embedding**

In [11]:
chunks_embedding = model.encode(chunks, convert_to_numpy=True)
print("Shape: ", chunks_embedding.shape)
chunks_embedding

Shape:  (378, 1024)

array([[ 0.5831421 ,  0.01211701, -0.22931232, ...,  0.0956009 ,
         0.28513888, -0.08372404],
       [ 0.6605553 , -0.13593258, -0.17265643, ..., -0.01612344,
         0.11497779,  0.08793126],
       [ 0.5812895 , -0.2690465 ,  0.30170736, ...,  0.12867296,
         0.48447734, -0.4153752 ],
       ...,
       [ 0.4819529 , -0.43881786,  0.03134119, ..., -0.1581173 ,
        -0.04589377, -0.0895991 ],
       [ 0.33758026, -0.75530684,  0.35650203, ..., -0.3526304 ,
         0.12827727, -0.05234856],
       [ 0.847971  , -0.2267644 ,  0.19055344, ...,  0.10415933,
         0.36788565, -0.19434743]], shape=(378, 1024), dtype=float32)

**Query embedding**

In [13]:
# Query sentences:
queries = [
    "dérogations",
    "dérogation",
    "derogation",
    "derogations",
    "animateur analyste.",
    "dérogations hors norme.",
    "règlement des impayés",
    "impayés",
    "impayé",
    "multi détention",
    "gestion des doublons de dossier",
    "résiliations"
]

# queries_cleaned = [light_cleaning(query) for query in queries]
queries_cleaned = light_cleaning(queries)
queries_embedding = model.encode(queries_cleaned, convert_to_numpy=True)
top_k = min(5, len(documents))

for i, query_embedding in enumerate(queries_embedding):
    print(queries[i])
    similarities = model.similarity(queries_embedding[i], chunks_embedding)[0].numpy()
    # print(similarities.shape)
    index_scores = similarities.argsort()
    # print(index_scores)

    counter = 0
    indexes_result = []
    for j in index_scores[::-1]:
        if indexes_documents[j] in indexes_result:
            continue
        print(f" - {titles[indexes_documents[j]]: <50}: {similarities[j]:.4f}")
        indexes_result.append(indexes_documents[j])
        if len(indexes_result) == top_k:
            break

dérogations
 - derogations a valider pp07                        : 0.4921
 - process hors norme 004                            : 0.4719
 - derogations mise à jour 04.2025                   : 0.4531
 - reclamations                                      : 0.3952
 - dérogations pp07 - l'essentiel                    : 0.3931
dérogation
 - derogations a valider pp07                        : 0.4117
 - process hors norme 004                            : 0.3675
 - derogations mise à jour 04.2025                   : 0.3546
 - dérogations pp07 - l'essentiel                    : 0.3362
 - reedition des contrats suite dysfonctionnement impression: 0.3324
derogation
 - derogations a valider pp07                        : 0.4886
 - reclamations                                      : 0.3742
 - process hors norme 004                            : 0.3641
 - derogations mise à jour 04.2025                   : 0.3380
 - 02 - process réclamations                         : 0.3143
derogations
 - derogations a valider pp07                        : 0.3850
 - reclamations                                      : 0.2875
 - process hors norme 004                            : 0.2812
 - derogations mise à jour 04.2025                   : 0.2568
 - analyser un impayé                                : 0.2500
animateur analyste.
 - aav - dérogations d08 - d10                       : 0.3289
 - 02 - process réclamations                         : 0.2829
 - derogations a valider pp07                        : 0.2170
 - la charte ave réclamations                        : 0.2095
 - process hors norme 004                            : 0.1922
dérogations hors norme.
 - process hors norme 004                            : 0.6710
 - derogations mise à jour 04.2025                   : 0.4464
 - derogations a valider pp07                        : 0.4149
 - dérogations pp07 - l'essentiel                    : 0.3425
 - reclamations                                      : 0.3366
règlement des impayés
 - automatisation des impayés                        : 0.6175
 - dérogations pp07 - l'essentiel                    : 0.5562
 - analyser un impayé                                : 0.5463
 - fiche de renseignement regul impaye pacifica      : 0.5387
 - derogations mise à jour 04.2025                   : 0.5096
impayés
 - automatisation des impayés                        : 0.4749
 - analyser un impayé                                : 0.4147
 - dérogations pp07 - l'essentiel                    : 0.3972
 - integration guadeloupe 17 10 2022 suivi du lancement: 0.3888
 - fiche de renseignement regul impaye pacifica      : 0.3886
impayé
 - automatisation des impayés                        : 0.1587
 - derogations a valider pp07                        : 0.1535
 - process hors norme 004                            : 0.1453
 - dérogations pp07 - l'essentiel                    : 0.1450
 - aav - dérogations d08 - d10                       : 0.1442
multi détention
 - dedoublonnage pacifica                            : 0.2253
 - process hors norme 004                            : 0.2066
 - 02 - process réclamations                         : 0.2021
 - automatisation des impayés                        : 0.1956
 - derogations mise à jour 04.2025                   : 0.1902
gestion des doublons de dossier
 - dedoublonnage pacifica                            : 0.4396
 - automatisation des impayés                        : 0.4243
 - reedition des contrats suite dysfonctionnement impression: 0.3766
 - 02 - process réclamations                         : 0.3597
 - reclamations                                      : 0.3456
résiliations
 - dérogations pp07 - l'essentiel                    : 0.3812
 - derogations a valider pp07                        : 0.3798
 - integration guadeloupe 17 10 2022 suivi du lancement: 0.3657
 - derogations mise à jour 04.2025                   : 0.3417
 - analyser un impayé                                : 0.2996

## all-minilm-l6-v2

**Locally load the model (NOT WORKING)**

In [ ]:
# model = SentenceTransformer(r"C:\Users\S589669\Documents\DEV\ABP-Doctheque\all-minilm-l6-v2-tensorflow2-default-v1",
#                             local_files_only=True, word_embedding_dimension = 512)

model = SentenceTransformer(r"C:\Users\S589669\Documents\DEV\ABP-Doctheque\all-minilm-l6-v2-tensorflow2-default-v1", local_files_only=True)
model.encode("Hello")

## Indexation with FAISS